name: micro_flutter_9615
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  go_router: ^10.1.0
  dio: ^5.3.0
  retrofit: ^3.0.1+1
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^1.5.3
  freezed_annotation: ^2.0.3
  url_launcher: ^6.1.2
  no_context_navigation: ^2.1.2

  # feature packages
  flutter_common_9615:
    path: features/flutter_common_9615
  flutter_home_9615:
    path: features/flutter_home_9615

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  retrofit_generator: ^4.0.1
  json_serializable: ^6.7.1
  melos: ^3.1.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true